image: "gitlab.autsoft.hu:4567/devops/androidciimage:latest"

########## Global settings ##########

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - .android/build-cache/

stages:
  - build base library
  - build modules
  - build demo app
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=.gradle
  - export ANDROID_SDK_HOME=$CI_PROJECT_DIR
  - mkdir .gradle && echo "org.gradle.jvmargs=-Xmx4096m -XX\:+HeapDumpOnOutOfMemoryError -Dfile.encoding\=UTF-8" > .gradle/gradle.properties
  - chmod +x ./gradlew

########## Job templates ##########

.build: &build
  tags:
    - docker
  script:
    - >
      ./gradlew
      ${MODULE_NAME}:assembleRelease
      ${MODULE_NAME}:androidSourcesJar
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "*/build"
    expire_in: 2 hours

.instrumentationTest: &instrumentationTest
  stage: test
  tags:
    - android
  before_script:
    - echo UI teszt
  script:
    - ./gradlew ${MODULE_NAME}:connectedAndroidTest
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "*/build"
    expire_in: 2 hours
  except:
    - tags

.deployArtifactory: &deployArtifactory
  stage: deploy
  tags:
    - docker
  script:
    - ./gradlew ${MODULE_NAME}:uploadArchives
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "*/build"
    expire_in: 2 hours
  only:
    - /^.*-RELEASE$/

########## Concrete jobs ##########

### Base library build ###

rainbow-cake build:
  <<: *build
  stage: build base library
  variables:
    MODULE_NAME: rainbow-cake

### Module library builds ###

rainbow-cake-timber build:
  <<: *build
  stage: build modules
  variables:
    MODULE_NAME: rainbow-cake-timber

### Demo app build ###

demo app build:
  <<: *build
  stage: build demo app
  variables:
    MODULE_NAME: demo

### Tests ###

rainbow-cake instrumentation test:
  <<: *instrumentationTest
  variables:
    MODULE_NAME: rainbow-cake

### Deployment ###

rainbow-cake deploy to artifactory:
  <<: *deployArtifactory
  variables:
    MODULE_NAME: rainbow-cake

rainbow-cake-timber deploy to artifactory:
  <<: *deployArtifactory
  variables:
    MODULE_NAME: rainbow-cake-timber
