image: registry.gitlab.com/hardysim/android-ci:latest

########## Global settings ##########

cache:
  paths:
    - .gradle
    - .android/build-cache/

stages:
  - build base library
  - build modules
  - demo app build
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=.gradle
  - export ANDROID_SDK_HOME=$CI_PROJECT_DIR
  - mkdir .gradle && echo "org.gradle.jvmargs=-Xmx4096m -XX\:+HeapDumpOnOutOfMemoryError -Dfile.encoding\=UTF-8" > .gradle/gradle.properties
  - chmod +x ./gradlew

########## Job templates ##########

.debugBuild: &debugBuild
  tags:
    - docker
  script:
    - >
      ./gradlew
      ${MODULE_NAME}:assembleDebug
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "*/build"
    expire_in: 2 hours
  except:
    - tags

.releaseBuild: &releaseBuild
  tags:
    - docker
  script:
    - >
      ./gradlew
      ${MODULE_NAME}:assembleRelease
      ${MODULE_NAME}:androidSourcesJar
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "*/build"
    expire_in: 2 hours
  only:
    - /^.*-RELEASE$/

.instrumentationTest: &instrumentationTest
  stage: test
  tags:
    - android
  before_script:
    - echo UI teszt
  script:
    - ./gradlew ${MODULE_NAME}:connectedAndroidTest
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "*/build"
    expire_in: 2 hours
  except:
    - tags

.deployMavenCentral: &deployMavenCentral
  stage: deploy
  tags:
    - docker
  before_script:
    - echo $GPG_KEY_CONTENTS | base64 -d > /secret.gpg
  script:
    - ./gradlew ${MODULE_NAME}:uploadArchives
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "*/build"
    expire_in: 2 hours
  only:
    - /^.*-RELEASE$/

########## Concrete jobs ##########

### Base library build ###

rainbow-cake-core debug build:
  <<: *debugBuild
  stage: build base library
  variables:
    MODULE_NAME: rainbow-cake-core

rainbow-cake-core release build:
  <<: *releaseBuild
  stage: build base library
  variables:
    MODULE_NAME: rainbow-cake-core

### Module library builds ###

rainbow-cake-timber debug build:
  <<: *debugBuild
  stage: build modules
  variables:
    MODULE_NAME: rainbow-cake-timber

rainbow-cake-timber release build:
  <<: *releaseBuild
  stage: build modules
  variables:
    MODULE_NAME: rainbow-cake-timber

rainbow-cake-navigation debug build:
  <<: *debugBuild
  stage: build modules
  variables:
    MODULE_NAME: rainbow-cake-navigation

rainbow-cake-navigation release build:
  <<: *releaseBuild
  stage: build modules
  variables:
    MODULE_NAME: rainbow-cake-navigation

rainbow-cake-channels debug build:
  <<: *debugBuild
  stage: build modules
  variables:
    MODULE_NAME: rainbow-cake-channels

rainbow-cake-channels release build:
  <<: *releaseBuild
  stage: build modules
  variables:
    MODULE_NAME: rainbow-cake-channels

### Demo app build ###

demo app debug build:
  <<: *debugBuild
  stage: demo app build
  variables:
    MODULE_NAME: demo
  dependencies:
    - rainbow-cake-core debug build
    - rainbow-cake-timber debug build
    - rainbow-cake-navigation debug build

### Tests ###

rainbow-cake-core instrumentation test:
  <<: *instrumentationTest
  variables:
    MODULE_NAME: rainbow-cake-core
  dependencies:
    - rainbow-cake-core debug build

rainbow-cake-navigation instrumentation test:
  <<: *instrumentationTest
  variables:
    MODULE_NAME: rainbow-cake-navigation
  dependencies:
    - rainbow-cake-navigation debug build

### Deployment ###

rainbow-cake-core deploy to mavencentral:
  <<: *deployMavenCentral
  variables:
    MODULE_NAME: rainbow-cake-core
  dependencies:
    - rainbow-cake-core release build

rainbow-cake-timber deploy to mavencentral:
  <<: *deployMavenCentral
  variables:
    MODULE_NAME: rainbow-cake-timber
  dependencies:
    - rainbow-cake-timber release build

rainbow-cake-navigation deploy to mavencentral:
  <<: *deployMavenCentral
  variables:
    MODULE_NAME: rainbow-cake-navigation
  dependencies:
    - rainbow-cake-navigation release build

rainbow-cake-channels deploy to mavencentral:
  <<: *deployMavenCentral
  variables:
    MODULE_NAME: rainbow-cake-channels
  dependencies:
    - rainbow-cake-channels release build
