image: registry.gitlab.com/hardysim/android-ci:latest

stages:
  - build
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=.gradle
  - export ANDROID_SDK_HOME=$CI_PROJECT_DIR
  - mkdir .gradle && echo "org.gradle.jvmargs=-Xmx4096m -XX\:+HeapDumpOnOutOfMemoryError -Dfile.encoding\=UTF-8" > .gradle/gradle.properties
  - chmod +x ./gradlew

debug build:
  stage: build
  tags:
    - docker
  script:
    - ./gradlew assembleDebug
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "*/build"
    expire_in: 2 hours
  except:
    - tags

instrumentation test:
  stage: test
  tags:
    - android
  before_script:
    - echo UI teszt
  script:
    - ./gradlew connectedAndroidTest
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "*/build"
    expire_in: 2 hours
  except:
    - tags
  dependencies:
    - debug build

release build:
  stage: build
  tags:
    - docker
  script:
    - ./gradlew assembleRelease androidSourcesJar
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "*/build"
    expire_in: 2 hours
  only:
    - /^.*-RELEASE$/

deploy to mavencentral:
  stage: deploy
  tags:
    - docker
  before_script:
    - echo $GPG_KEY_CONTENTS | base64 -d > /secret.gpg
    - ls -al /
  script:
    - ./gradlew uploadArchives
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - "*/build"
    expire_in: 2 hours
  only:
    - /^.*-RELEASE$/
  dependencies:
    - release build
